### PR TITLE
[_62] rename ssl module (4-2-stable)

### PR DESCRIPTION
**Pull request by d-w-moore**
See main branch PR for explanation : https://github.com/irods/irods_testing_environment/pull/69

### CODE REVIEW

**Comment by trel** [comment]
oh, interesting.     good find.

should we consider/pick a better name, overall?  rather than just a case-change?

**Comment by d-w-moore** [comment]
I am going to defer to @alanking on that.  a - I'm still testing , and b - I'm still trying to figure out how it fits into the whole scheme of things, let alone what it should be called ...

**Comment by d-w-moore** [comment]
Perhaps `ssl_utilities` ?
I think I was confused, just now, because my fix didn't appear to work, but it seems to have been I'd forgotten to delete what was still there in the **REPO_ROOT/**` irods_testing_environment/__pycache__/ssl.cpython-36.pyc` . (Unwelcome bytecode hanging around is one of the biggest bugaboos ever.)

**Comment by korydraughn** [comment]
If `ssl_setup` fits the pattern, I think we should continue with that.

Is there some specific criteria for determining if a file should use the `_setup` suffix?

**Comment by alanking** [comment]
Not really. These have been broken up specifically so that a `utils.py` does not exist :p So I had to come up with some names. Completely open to changing these

**Comment by trel** [comment]
looks good - please squash

**Comment by d-w-moore** [comment]
Yes, will test "from zero" then squash...

**Comment by d-w-moore** [comment]
ok - tested, and is fine on 4-2-stable. will squash, (not yet #) and cherry pick to master

**Comment by trel** [comment]
looks good to me, awaiting an alan to agree.

**Review by alanking — APPROVED** [review]
Yep, # em

**Pull request merged**
