### PR TITLE
[irods/irods#7191] Add Rocky Linux 9 support

### PR DESCRIPTION
**Pull request by alanking**
In service of irods/irods#7191

Copied from files for rockylinux:8. Unit tests pass, core tests are running (and passing, so far). Need to try out mysql

Same caveats apply here regarding irods/irods#7349

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]
Ship it.

**Comment by alanking** [comment]
Somehow this was working on the first few runs, but a subsequent run revealed that `procps` is required for our scripts. Still working through this, apparently

**Comment by alanking** [comment]
Testing has been going well, so I think this is good to go. mysql works fine as well.

@korydraughn - I see that you requested a review from yourself, so I will hold off on merging until you give the green light.

**Comment by korydraughn** [comment]
So the issue with `procps` is all good now?

**Review by korydraughn — APPROVED** [review]
Pound it.

**Pull request merged**
