### PR TITLE
[#167] Add mariadb projects

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #167

Until irods/irods#7323 (and other irods issues with mariadb) is(are) fixed, expect test failures when using these projects. In many cases, irods setup will fail.

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
Looks good overall. Is there a reason that we are differentiating the minor versions for mariadb? I'm recalling that we moved away from that recently for Postgres, so just wanted to understand why.

**Comment by SwooshyCueb** [comment]
Postgres's versioning system is different from MySQL's and MariaDB's. I think I explained it in the Postgres issue

**Review by alanking — APPROVED** [review]
Got it. Let's # it, then

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
