### PR TITLE
incorporate this repository's 4-2-stable branch into main

### PR DESCRIPTION
**Pull request by alanking**

### CODE REVIEW

**Comment by trel** [comment]
oh dear.  really?

why can't it be... rebased?

**Comment by alanking** [comment]
Going to put this in draft form til I can work out the merge issue

**Comment by alanking** [comment]
I'm pretty much ready to merge this and delete the 4-2-stable branch if everybody's good with that. Will merge sometime this afternoon if no thoughts are provided.

**Comment by alanking** [comment]
I'm pretty much ready to merge this and delete the 4-2-stable branch if everybody's good with that. Will merge sometime this afternoon if no thoughts are provided.

**Comment by trel** [comment]
get down to single commit first?

**Comment by alanking** [comment]
Squashed - no # yet.

**Comment by trel** [comment]
Yes, if this is running, # it up.

**Comment by alanking** [comment]
Cool, thanks! Merging.

**Pull request merged**
