### PR TITLE
Add support for federation and running test_federation

### PR DESCRIPTION
**Pull request by alanking**
Federation is not as flexible as one would hope right now, but it works. Found a bug in federation for 4.2.8+ which is not affected by this change

### CODE REVIEW

**Review by trel — COMMENTED** [review]
massive.

i believe issue 10 is available...

**Comment by alanking** [comment]
Okay. Some of these things are refactoring and more general improvements, and then there are the changes for federation. Should I just squash it all into 1?

**Comment by trel** [comment]
squash to taste.   federation things should reference 10.

**Comment by alanking** [comment]
Eh, it's all part of the effort. Squashed and #'d

**Pull request merged**
