### PR TITLE
[#215,#216,irods/irods#7592] Add MySQL 8.4 projects, disambiguate MySQL 8.0 projects, update MySQL 8.0 ODBC connector, add Ubuntu 24.04 to readme

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #215
Addresses #216
In service of irods/irods#7592

The new 8.4 projects may not be useful until irods/irods#7495 is fixed.

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
Looks good overall.

Is there a reason for the selected platforms getting 8.4 projects and not others? For example, I see that Debian 11 has MySQL 8.4 ODBC drivers available, but no new project. Just wanted to understand why.

**Comment by SwooshyCueb** [comment]
> Is there a reason for the selected platforms getting 8.4 projects and not others? For example, I see that Debian 11 has MySQL 8.4 ODBC drivers available, but no new project. Just wanted to understand why.

It's not related to the ODBC driver. Unless something changed since 8.3, you can use 8.0 drivers with 8.4 and vise versa.

We have an existing pattern of older distros not always getting projects for newer database versions. Take a look at the projects before my recent changes. [Debian 11](https://github.com/irods/irods_testing_environment/tree/f2cfbd835868a56671e10f264d8c4403a7ed6570/projects/debian-11), [Rocky Linux 8](https://github.com/irods/irods_testing_environment/tree/f2cfbd835868a56671e10f264d8c4403a7ed6570/projects/rockylinux-8), [Almalinux 8](https://github.com/irods/irods_testing_environment/tree/f2cfbd835868a56671e10f264d8c4403a7ed6570/projects/almalinux-8), and [CentOS 7](https://github.com/irods/irods_testing_environment/tree/f2cfbd835868a56671e10f264d8c4403a7ed6570/projects/centos-7) had no Postgres 14 project.
Given that EL7 is going EOL in less than a week, Debian 11 is going EOL next month-ish, and Ubuntu 20.04 isn't supported by MySQL 8.4; it made sense to me to follow the existing pattern.

**Review by alanking — APPROVED** [review]
Ah, okay. The Debian 11 was the most curious to me but I didn't realize it was so close to EOL. This all checks out, thanks. Let's # it

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
