### PR TITLE
Support main for ubuntu:18.04

### PR DESCRIPTION
**Pull request by alanking**
Installs python3 (and python3-pip, etc.) on base image and replaces all
calls to python with python3 in the scripts and library.

### CODE REVIEW

**Comment by alanking** [comment]
Other platforms will be added once I can manage to build them. This is the only platform (besides centos:7?) being carried forward to 4.3.x

**Comment by trel** [comment]
Yes, CentOS7 and Ubuntu18 carry forward.  Dropping Ubuntu16.

**Review by trel — COMMENTED** [review]
looks good to me

**Comment by alanking** [comment]
Okay. Let me see if I can't get centos:7 on board before merging

**Comment by alanking** [comment]
centos:7 not there yet. Merging

**Pull request merged**
