### PR TITLE
Align test times by right justifying with fixed number of decimals

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Comment by d-w-moore** [comment]
As it contains some commits from @alanking's dev branch  [here](https://github.com/alanking/irods_testing_environment/tree/pluginz) , this PR  is contingent on that branch being merged.

**Comment by alanking** [comment]
I cherry-picked your change in this PR: https://github.com/irods/irods_testing_environment/pull/85

Let's leave this open until that gets merged. Thanks for your patience :)

**Comment by d-w-moore** [comment]
Cool cool !

**Comment by alanking** [comment]
#85 is now merged. This can be closed.

**Comment by trel** [comment]
closed because the same effort is captured in #85?

**Comment by alanking** [comment]
Yes, I cherry-picked the last commit by @d-w-moore  and it is now merged.

**Pull request closed without merging**
