### PR TITLE
Update README for clarity and ease of use

### PR DESCRIPTION
**Pull request by alanking**
- Update usage notes for standing up and running various test flavors

- Add extensive details to the type of directory structure expected by
plugin test hooks, which are used by run_plugin_tests.py

--- 

Still thinking about what else to add to this but figured I'd put it up here for viewing

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Reads well.

I took a look at the full rendering. You mention the acronyms CSP and CSC, but not what they stand for.

Consider changing the title, *Quick Start*, to something more specific (e.g. *Standing Up A Single Zone*). The content of that section doesn't match the title IMO.

You could also try moving the *Quick Start* section after the *Run iRODS Tests* section since *Run iRODS Tests* specifically goes over the primary use of this project, which is running tests. The *Quick Start* section feels more like a good thing to know exists.

**Comment by alanking** [comment]
Oops, I will address the more general comments shortly

**Comment by alanking** [comment]
For convenient viewing: https://github.com/alanking/irods_testing_environment/tree/remote

**Comment by korydraughn** [comment]
The current text reads fine to me. The only thing that can make it slightly better is to mention the `--help` option (if we aren't already). That way, the README doesn't have to cover every option and users have a place they can look for additional options.

**Review by korydraughn — APPROVED** [review]
If you're happy with it, ship it!

**Pull request merged**
