### PR TITLE
[#203] Ensure all required packages can be found

### PR DESCRIPTION
**Pull request by MartinFlores751**
Fix rockylinux-9 package install issues.

It should be all spaces now.

### CODE REVIEW

**Review by SwooshyCueb — APPROVED** [review]

**Review by korydraughn — COMMENTED** [review]
Let's get an issue number on this and we'll approve it.

**Comment by MartinFlores751** [comment]
Done.

**Review by korydraughn — APPROVED** [review]
Pound it.

**Comment by MartinFlores751** [comment]
It's got the '#'.

**Review by alanking — APPROVED** [review]

**Pull request merged**
